----------------------------------        RUN AS SYS !!!!!           ---------------------------
/
SELECT VALUE FROM V$OPTION WHERE PARAMETER='Oracle Label Security';
select status from dba_ols_status where name ='OLS_CONFIGURE_STATUS';
/
--EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
/
SHUTDOWN IMMEDIATE;
STARTUP;
/
ALTER PLUGGABLE DATABASE XEPDB1 OPEN READ WRITE;
ALTER SESSION SET CONTAINER=XEPDB1;
--ALTER SESSION SET CONTAINER=CDB$ROOT;
/
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
/
CREATE USER OLS_TEST1 IDENTIFIED BY 123 CONTAINER = CURRENT;
SHOW CON_NAME
CREATE USER AD_OLS IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO OLS_TEST1;
ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK CONTAINER = ALL;
GRANT UNLIMITED TABLESPACE TO OLS_TEST1;
GRANT LBAC_DBA TO AD_OLS;
GRANT SELECT ANY DICTIONARY TO AD_OLS;
GRANT LBAC_DBA TO OLS_TEST1;
GRANT SELECT ANY DICTIONARY TO OLS_TEST1;
/

GRANT EXECUTE ON sa_components TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON sa_SESSION TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON sa_label_admin TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON sa_audit_admin  TO ols_test1 WITH GRANT OPTION;
GRANT EXECUTE ON SA_SYSDBA TO OLS_TEST1;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO OLS_TEST1;
--GRANT QLNV_DBA TO OLS_TEST1;

/


--SELECT * FROM DBA_SA_LEVELS;
--SELECT * FROM dba_sa_compartments;
--SELECT * FROM DBA_SA_GROUPS;