

--------------------------------------RUN 1 TIME ONLY !!!!!!!----------------------------------------------

--LEVEL GIAMDOC>TRUONGPHONG>NHANVIEN
--COMPARTMENT: MUA BAN, SAN XUAT, GIA CONG
--GROUP MIEN BAC, TRUNG, NAM
BEGIN
sa_sysdba.create_policy
(policy_name => 'QLNV',
column_name => 'QLNV_label');
END;
/
EXEC SA_SYSDBA.ENABLE_POLICY('QLNV');
/
--EXEC SA_COMPONENTS.DROP_LEVEL('QLNV','GD');
EXEC SA_COMPONENTS.CREATE_LEVEL('QLNV',120,'GD','BANGIAMDOC');
EXEC SA_COMPONENTS.CREATE_LEVEL('QLNV',100,'TP','TRUONGPHONG');
EXEC SA_COMPONENTS.CREATE_LEVEL('QLNV',80,'NV','NHANVIEN');
/
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('QLNV',80,'MB','MUABAN');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('QLNV',100,'SX','SANXUAT');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('QLNV',120,'GC','GIACONG');
/
EXEC SA_COMPONENTS.CREATE_GROUP('QLNV',80,'MB','MIENBAC');
EXEC SA_COMPONENTS.CREATE_GROUP('QLNV',100,'MT','MIENTRUNG');
EXEC SA_COMPONENTS.CREATE_GROUP('QLNV',120,'MN','MIENNAM');
/
EXEC SA_USER_ADMIN.SET_USER_PRIVS('QLNV','OLS_TEST1','FULL,PROFILE_ACCESS');
/
CREATE OR REPLACE FUNCTION GET_STAFF_LABEL (P_LEVEL IN VARCHAR2, P_COMPARTMENT IN VARCHAR2,
P_GROUP IN VARCHAR2)
RETURN VARCHAR AS V_LABEL VARCHAR2(80);
BEGIN
    IF P_LEVEL = 'BANGIAMDOC' THEN
    V_LABEL:='GD:';
    ELSIF P_LEVEL = 'TRUONGPHONG' THEN
    V_LABEL:='TP:';
    ELSE
    V_LABEL:='NV:';
    END IF;
    
    IF P_COMPARTMENT='MUABAN' THEN
    V_LABEL:=V_LABEL||'MB:'; -- GDMB
    ELSIF P_COMPARTMENT='SANXUAT' THEN
    V_LABEL:=V_LABEL||'SX:';
    ELSE
    V_LABEL:=V_LABEL||'GC:';
    END IF;
    
    IF P_GROUP='MIENBAC' THEN
    V_LABEL:=V_LABEL||'MB'; -- GDMB
    ELSIF P_GROUP='MIENTRUNG' THEN
    V_LABEL:=V_LABEL||'MT';
    ELSE
    V_LABEL:=V_LABEL||'MN';
    END IF;
    
    RETURN CHAR_TO_LABEL('QLNV',V_LABEL);
    END GET_STAFF_LABEL;
/
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME=>'QLNV',
    SCHEMA_NAME=>'OLS_TEST1',
    TABLE_NAME=>'THONGBAO',
    TABLE_OPTIONS=>'NO_CONTROL');
END;
/

/
--KHOI TAO NHAN

DECLARE
    CURSOR CUR IS SELECT UPPER(DOUUTIEN),UPPER(LINHVUC),UPPER(CHINHANH) FROM THONGBAO;
    DUT VARCHAR2(50);
    LV VARCHAR2(50);
    CN VARCHAR2(50);
    CNT INT := 1;
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO DUT,LV,CN;
        IF CUR%NOTFOUND THEN
            EXIT;
        END IF;
            UPDATE THONGBAO
            SET QLNV_LABEL = GET_STAFF_LABEL(DUT,LV,CN) WHERE STT=CNT;
    CNT:=CNT+1;
    END LOOP;
    CLOSE CUR;
    COMMIT;
END;
/
SELECT * FROM THONGBAO;
--SELECT GET_STAFF_LABEL('BANGIAMDOC','SANXUAT','MIENTRUNG') FROM DUAL;
/
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('QLNV','OLS_TEST1','THONGBAO');

SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME => 'QLNV',
    SCHEMA_NAME => 'OLS_TEST1',
    TABLE_NAME=>'THONGBAO',
    TABLE_OPTIONS =>'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL',
    PREDICATE=>NULL
);
END;
/

--Chay test: 
-----------------------------------------------------*Nho grant role lai cho USER40
----------------------------------------------------------------------------
--EXECUTE SA_USER_ADMIN.SET_USER_LABELS('QLNV','NV0001','GD:MB,SX,GC:MB,MT,MN');
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('QLNV','NV0001','READ');
--GRANT SELECT ON OLS_TEST1.THONGBAO TO NV0001;
--
--EXECUTE SA_USER_ADMIN.SET_USER_LABELS('QLNV','NV0002','TP:MB:MB');
--GRANT SELECT ON OLS_TEST1.THONGBAO TO NV0002;
----
--EXECUTE SA_USER_ADMIN.SET_USER_LABELS('QLNV','NV0040','TP:SX:MN');
--GRANT SELECT ON OLS_TEST1.THONGBAO TO NV0040;
----
--EXECUTE SA_USER_ADMIN.SET_USER_LABELS('QLNV','NV0005','GD:MB,SX,GC:MB,MT,MN');
--GRANT SELECT ON OLS_TEST1.THONGBAO TO NV0005;
--
--EXECUTE SA_USER_ADMIN.SET_USER_LABELS('QLNV','NV0003','GD:MB,SX,GC');
--GRANT SELECT ON OLS_TEST1.THONGBAO TO NV0003;
/
--SELECT * FROM DBA_SA_LEVELS;
--SELECT * FROM dba_sa_compartments;
--SELECT * FROM DBA_SA_GROUPS;
--
--SELECT * FROM DBA_SA_USERS;
