/*
show con_name
select * from ols_test1.nhanvien;
alter session set "_ORACLE_SCRIPT"=true;
GRANT ALL PRIVILEGES TO OLS_TEST1 WITH ADMIN OPTION;
set serveroutput on size unlimited;
*/
SHOW CON_NAME
--QUAN TRONG 
SELECT * FROM DBA_ROLE_PRIVS ;
/
--tao user
create or replace procedure usp_CreateUser
as
    CURSOR CUR IS SELECT 'NV' || MANV FROM NHANVIEN WHERE ('NV' || MANV) NOT IN (SELECT USERNAME FROM ALL_USERS);
    str varchar(1000);
    usr varchar2(30);
begin
    open cur;
    --str := 'alter session set "_ORACLE_SCRIPT"=true';
    --execute immediate(str);
    loop
        fetch cur into usr;
        exit when cur%NOTFOUND;
        str:='create user '||usr||' identified by '||usr;
        execute immediate(str);
        STR:='GRANT CREATE SESSION TO '||USR;
        EXECUTE IMMEDIATE (STR);
    end loop;
    --str := 'alter session set "_ORACLE_SCRIPT"=false';
    --execute immediate(str);
end;
/
-- tao procdure de xoa user trong bang docgia
create or replace procedure usp_DropUser
as
    CURSOR CUR IS SELECT 'NV' || MANV FROM NHANVIEN WHERE ('NV' || MANV) IN (SELECT USERNAME FROM ALL_USERS);
    str varchar(1000);
    usr varchar2(30);
begin
    open cur;
    --str := 'alter session set "_ORACLE_SCRIPT"=true';
    --execute immediate(str);
    loop
        fetch cur into usr;
        exit when cur%NOTFOUND;
        str:='drop user '||usr||' cascade';
        execute immediate(str);
    end loop;
    
    --str := 'alter session set "_ORACLE_SCRIPT"=false';
    --execute immediate(str);

end;
/
EXECUTE USP_DROPUSER;
EXECUTE USP_CREATEUSER;
/
--create user OLS_TEST1 identified by 123;
--grant create session to OLS_TEST1;
GRANT ALL PRIVILEGES TO OLS_TEST1 WITH ADMIN OPTION;
-- CAC PROCEDURE DUNG CHUNG
/
CREATE OR REPLACE PROCEDURE GRANT_VT_TAB_PRIV(VT VARCHAR2, TAB VARCHAR2,PRIV VARCHAR2)
AS
    CURSOR CUR IS 
    (
        SELECT 'NV'||MANV FROM OLS_TEST1.NHANVIEN
        WHERE UPPER(VAITRO)=VT
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    --Dbms_ouTput.Put_line('1');
    OPEN CUR;
    --STR := 'alter session set "_ORACLE_SCRIPT"=true';
    --EXECUTE IMMEDIATE (STR);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STR:='GRANT '||PRIV||' ON '||TAB||' TO '||USR;
        Dbms_ouTput.Put_line(STR);
        EXECUTE IMMEDIATE(STR);
    END LOOP;
    --STR:= 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    --EXECUTE IMMEDIATE(STR);
END;
/
EXECUTE GRANT_VT_TAB_PRIV('NHANVIEN','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('QUANLYTRUCTIEP','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('TRUONGPHONG','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('TAICHINH','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('NHANSU','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('TRUONGDEAN','OLS_TEST1.F_VAITRO','EXECUTE');
EXECUTE GRANT_VT_TAB_PRIV('BANGIAMDOC','OLS_TEST1.F_VAITRO','EXECUTE')
/

CREATE OR REPLACE PROCEDURE GRANT_ROLE_NV (ROL VARCHAR2)
AS
    CURSOR CUR IS 
    (
        SELECT 'NV'||MANV FROM OLS_TEST1.NHANVIEN
        WHERE UPPER('NV'||MANV) IN (SELECT USERNAME FROM ALL_USERS) AND UPPER(VAITRO)=ROL
    );
    STR VARCHAR(1000);
    USR VARCHAR2(30);
BEGIN
    OPEN CUR;
    --STR := 'alter session set "_ORACLE_SCRIPT"=true';
    --EXECUTE IMMEDIATE(STR);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STR:='GRANT '||ROL||' TO '||USR;
        execute immediate(STR);
    end loop;
    --STR := 'alter session set "_ORACLE_SCRIPT"=false';
    --EXECUTE IMMEDIATE(STR);
END;
/ 
/
CREATE OR REPLACE FUNCTION F_VAITRO(USRNAME VARCHAR2)
RETURN VARCHAR2
AS
    CURSOR CUR IS 
    (
        SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS
        WHERE UPPER(GRANTEE)=UPPER(USRNAME)
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    OPEN CUR;
    --STR := 'alter session set "_ORACLE_SCRIPT"=true';
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STR:=USR;
    END LOOP;
    RETURN STR;
END;

/
--TAO ROLE
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE QUANLYTRUCTIEP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE TRUONGPHONG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE TAICHINH';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANSU';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE TRUONGDEAN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE BANGIAMDOC';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/
CREATE ROLE NHANVIEN;
CREATE ROLE QUANLYTRUCTIEP;
CREATE ROLE TRUONGPHONG;
CREATE ROLE TAICHINH;
CREATE ROLE NHANSU;
CREATE ROLE TRUONGDEAN;
CREATE ROLE BANGIAMDOC;
/
--TAO VIEW TREN BANG NHANVIEN
CREATE OR REPLACE VIEW V_NHANVIEN
AS
    SELECT MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,DECODE('NV'||MANV,USER,LUONG,NULL) LUONG,DECODE('NV'||MANV,USER,PHUCAP,NULL) PHUCAP,VAITRO,MANQL,PHG
    FROM OLS_TEST1.NHANVIEN;
/
--CAP QUYEN CHO CAC VAI TRO DUOC XEM 
--GRANT SELECT ON OLS_TEST1.V_NHANVIEN TO QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
/
--CHINH SACH 1
EXEC GRANT_ROLE_NV('NHANVIEN')
/
CREATE OR REPLACE VIEW V_NHANVIEN_NHANVIEN
AS
    SELECT *
    FROM OLS_TEST1.NHANVIEN
    WHERE 'NV'||MANV=USER;
/
CREATE OR REPLACE VIEW V_NHANVIEN_PHANCONG
AS
    SELECT *
    FROM OLS_TEST1.PHANCONG
    WHERE 'NV'||MANV=USER;
/
GRANT SELECT ON OLS_TEST1.V_NHANVIEN_NHANVIEN TO NHANVIEN,QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
GRANT SELECT ON OLS_TEST1.V_NHANVIEN_PHANCONG TO NHANVIEN,QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
GRANT SELECT ON OLS_TEST1.PHONGBAN TO NHANVIEN,QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
GRANT SELECT ON OLS_TEST1.DEAN TO NHANVIEN,QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
GRANT UPDATE (NGAYSINH,DIACHI,SODT) ON OLS_TEST1.V_NHANVIEN_NHANVIEN TO NHANVIEN,QUANLYTRUCTIEP,TRUONGPHONG,TAICHINH,NHANSU,TRUONGDEAN;
/
/
--EXECUTE GRANT_ROLE_NV;
--GRANT NHANVIEN TO NV0001;
/
--CHINH SACH 2:
/
--TAO ROLE
--CREATE ROLE QUANLYTRUCTIEP;
--GRANT QUANLYTRUCTIEP TO NV0001;
--REVOKE NHANVIEN FROM NV0001;
--SELECT * FROM all_users
--TAO FUNCTION HO TRO
EXEC GRANT_ROLE_NV('QUANLYTRUCTIEP');
/
--TAO POLICY TREN BANG NHANVIEN
CREATE OR REPLACE FUNCTION P_QUANLYTRUCTIEP_0(P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    USR VARCHAR(100);
BEGIN
    --USR:=SYS_CONTEXT('USERENV','SESSION_USER');
    IF(UPPER(OLS_TEST1.F_VAITRO(USER))='QUANLYTRUCTIEP') THEN
        --RETURN '0=1';
        RETURN 'UPPER(''NV''||MANQL) ='''||USER||''' OR UPPER(''NV''||MANV)='''||USER||'''';
    --ELSE
    --    RETURN '1=1';
    --IF(USER='NV0001') THEN
    --    RETURN '0=1';
    END IF;
    RETURN '1=1';
    --RETURN 'UPPER(MANQL) ='''||USR||'''';
END;
/
--TAO POLICY TREN BANG PHANCONG
CREATE OR REPLACE FUNCTION P_QUANLYTRUCTIEP_PC (P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    CURSOR CUR IS 
    (
        SELECT 'NV'||MANV FROM OLS_TEST1.NHANVIEN
        WHERE UPPER('NV'||MANQL)=USER
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(OLS_TEST1.F_VAITRO(USER))='QUANLYTRUCTIEP') THEN
        OPEN CUR;
        STR := 'UPPER(''NV''||MANV)='''||USER||'''';
        LOOP
            FETCH CUR INTO USR;
            EXIT WHEN CUR%NOTFOUND;
            STR:=STR||' OR UPPER(''NV''||MANV)='''||USR||'''';
        END LOOP;
        RETURN STR;
    ELSE
        RETURN '1=1';
    END IF;
END;
/
--ADD POLICY

BEGIN
    DBMS_RLS.DROP_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'V_NHANVIEN',
        POLICY_NAME=>'POLICY_QUANLYTRUCTIEP'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28102 THEN
            RAISE;
        END IF;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'V_NHANVIEN',
        POLICY_NAME=>'POLICY_QUANLYTRUCTIEP',
        POLICY_FUNCTION=>'P_QUANLYTRUCTIEP_0',
        STATEMENT_TYPES=>'SELECT',
        UPDATE_CHECK=>TRUE,
        SEC_RELEVANT_COLS=>'LUONG,PHUCAP'
        --SEC_RELEVANT_COLS_OPT=>DBMS_RLS.ALL_ROWS
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'PHANCONG',
        POLICY_NAME=>'POLICY_QUANLYTRUCTIEP_1'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28102 THEN
            RAISE;
        END IF;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'PHANCONG',
        POLICY_NAME=>'POLICY_QUANLYTRUCTIEP_1',
        POLICY_FUNCTION=>'P_QUANLYTRUCTIEP_PC',
        STATEMENT_TYPES=>'SELECT'
    );
END;
/
--CAP QUYEN TRUY VAN TREN 2 BANG NHANVIEN VA PHANCONG CHO VAI TRO QUANLYTRUCTIEP
--EXECUTE GRANT_VT_TAB_PRIV('QUANLYTRUCTIEP','OLS_TEST1.V_NHANVIEN','SELECT');
--EXECUTE GRANT_VT_TAB_PRIV('QUANLYTRUCTIEP','OLS_TEST1.PHANCONG','SELECT');
GRANT SELECT ON OLS_TEST1.V_NHANVIEN TO QUANLYTRUCTIEP;
GRANT SELECT ON OLS_TEST1.PHANCONG TO QUANLYTRUCTIEP;
/
--CHINH SACH 3
/
--TAO ROLE

EXEC GRANT_ROLE_NV('TRUONGPHONG');
/
--TAO POLICY TREN BANG NHANVIEN
CREATE OR REPLACE FUNCTION P_TRUONGPHONG(P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    CURSOR CUR IS 
    (
        SELECT DISTINCT MAPB FROM OLS_TEST1.PHONGBAN WHERE UPPER('NV'||TRPHG)=USER
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(OLS_TEST1.F_VAITRO(USER))='TRUONGPHONG') THEN
        OPEN CUR;
        LOOP
            FETCH CUR INTO USR;
            EXIT WHEN CUR%NOTFOUND;
            STR:='UPPER(PHG)='''||USR||'''';
        END LOOP;
        --Dbms_ouTput.Put_line(STR);
        RETURN STR;
    END IF;
    RETURN '1=1';
END;
/

--TAO POLICY TREN BANG PC
CREATE OR REPLACE FUNCTION P_TRUONGPHONG_PC(P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    CURSOR CUR IS 
    (
        SELECT MANV FROM OLS_TEST1.NHANVIEN WHERE PHG=(
        SELECT DISTINCT MAPB FROM OLS_TEST1.PHONGBAN WHERE UPPER('NV'||TRPHG)=USER)
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(F_VAITRO(USER))='TRUONGPHONG') THEN
        --RETURN '0=1';
        STR := 'UPPER(''NV''||MANV)='''||USER||'''';
        OPEN CUR;
        LOOP
            FETCH CUR INTO USR;
            EXIT WHEN CUR%NOTFOUND;
            STR:=STR||' OR UPPER(MANV)='''||USR||'''';
        END LOOP;
        RETURN STR;
    ELSE
        RETURN '1=1';
    END IF;
END;
/
--ADD POLICY

BEGIN
    DBMS_RLS.DROP_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'V_NHANVIEN',
        POLICY_NAME=>'POLICY_TRUONGPHONG'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28102 THEN
            RAISE;
        END IF;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'V_NHANVIEN',
        POLICY_NAME=>'POLICY_TRUONGPHONG',
        POLICY_FUNCTION=>'P_TRUONGPHONG',
        STATEMENT_TYPES=>'SELECT',
        SEC_RELEVANT_COLS=>'LUONG,PHUCAP'
        --SEC_RELEVANT_COLS_OPT=>DBMS_RLS.ALL_ROWS
    );
END;
/
BEGIN
    DBMS_RLS.DROP_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'PHANCONG',
        POLICY_NAME=>'POLICY_TRUONGPHONG_1'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28102 THEN
            RAISE;
        END IF;
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'PHANCONG',
        POLICY_NAME=>'POLICY_TRUONGPHONG_1',
        POLICY_FUNCTION=>'P_TRUONGPHONG_PC',
        STATEMENT_TYPES=>'DELETE,INSERT,UPDATE,SELECT',
        UPDATE_CHECK=>TRUE
    );
END;
/

--CAP QUYEN CAN THIET CHO VAI TRO TRUONG PHONG TREN 2 BANG NHANVIEN VA PHANCONG
--EXECUTE GRANT_VT_TAB_PRIV('TRUONGPHONG','OLS_TEST1.V_NHANVIEN','SELECT')
--EXECUTE GRANT_VT_TAB_PRIV('TRUONGPHONG','OLS_TEST1.PHANCONG','DELETE,INSERT,UPDATE,SELECT')
GRANT SELECT ON OLS_TEST1.V_NHANVIEN TO TRUONGPHONG;
GRANT SELECT,INSERT,DELETE,UPDATE ON OLS_TEST1.PHANCONG TO TRUONGPHONG;
/

--CHINH SACH 4:
--CAP ROLE
/
EXEC GRANT_ROLE_NV('TAICHINH');
/
--CAP QUYEN CHO VAI TRO TAI CHINH
EXECUTE GRANT_VT_TAB_PRIV('TAICHINH','OLS_TEST1.NHANVIEN','SELECT');
EXECUTE GRANT_VT_TAB_PRIV('TAICHINH','OLS_TEST1.PHANCONG','SELECT');
EXECUTE GRANT_VT_TAB_PRIV('TAICHINH','OLS_TEST1.NHANVIEN','UPDATE(LUONG,PHUCAP)')
/

--CHINH SACH 5:

EXEC GRANT_ROLE_NV('NHANSU');

EXECUTE GRANT_VT_TAB_PRIV('NHANSU','OLS_TEST1.V_NHANVIEN','SELECT');
EXECUTE GRANT_VT_TAB_PRIV('NHANSU','OLS_TEST1.PHONGBAN','INSERT,UPDATE');
EXECUTE GRANT_VT_TAB_PRIV('NHANSU','OLS_TEST1.V_NHANVIEN','INSERT(MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG),UPDATE(MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG)');

/*
--TAO POLICY
CREATE OR REPLACE FUNCTION P_NHANSU (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    IF(F_VAITRO(USER)='NHANSU') THEN
        RETURN 'LUONG IS NULL AND PHUCAP IS NULL';
    ELSE
        RETURN '1=1';
    END IF;
END;
*/
/

/*
--ADD POLICY
BEGIN
    DBMS_RLS.DROP_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'NHANVIEN',
        POLICY_NAME=>'POLICY_NHANSU'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -28102 THEN
            RAISE;
        END IF;
END;
*/
/*
BEGIN
    DBMS_RLS.ADD_POLICY
    (
        OBJECT_SCHEMA=>'OLS_TEST1',
        OBJECT_NAME=>'NHANVIEN',
        POLICY_NAME=>'POLICY_NHANSU',
        POLICY_FUNCTION=>'P_NHANSU',
        STATEMENT_TYPES=>'INSERT,UPDATE',
        UPDATE_CHECK=>TRUE
    );
END;
*/
--CHINH SACH 6:
EXEC GRANT_ROLE_NV('TRUONGDEAN');
EXECUTE GRANT_VT_TAB_PRIV('TRUONGDEAN','OLS_TEST1.DEAN','SELECT,INSERT,DELETE,UPDATE');
/
--CHINH SACH 7:
EXEC GRANT_ROLE_NV('BANGIAMDOC');
EXEC GRANT_VT_TAB_PRIV('BANGIAMDOC','OLS_TEST1.NHANVIEN','SELECT');
EXEC GRANT_VT_TAB_PRIV('BANGIAMDOC','OLS_TEST1.PHONGBAN','SELECT');
EXEC GRANT_VT_TAB_PRIV('BANGIAMDOC','OLS_TEST1.DEAN','SELECT');
EXEC GRANT_VT_TAB_PRIV('BANGIAMDOC','OLS_TEST1.PHANCONG','SELECT');

/



/-- TEST HÀM
/*
CREATE OR REPLACE PROCEDURE P_TEST
AS
    STR VARCHAR2(1000);
BEGIN
    STR:='1';
    Dbms_ouTput.Put_line(STR); 
    STR:=UPPER(OLS_TEST1.F_VAITRO('NV0007'));
    --IF STR='QUANLYTRUCTIEP' THEN
    Dbms_ouTput.Put_line(STR);
    --END IF;
END;
/

--TAO POLICY TREN BANG PC
CREATE OR REPLACE PROCEDURE P_TRUONGPHONG_TEST
AS
    CURSOR CUR IS 
    (
        SELECT MANV FROM NHANVIEN WHERE PHG=(
        SELECT DISTINCT MAPB FROM OLS_TEST1.PHONGBAN WHERE UPPER(TRPHG)='NV0007')
    );
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(F_VAITRO('NV0007'))='TRUONGPHONG') THEN
        OPEN CUR;
        LOOP
            STR := 'UPPER(MANV)='''||USER||'''';
            FETCH CUR INTO USR;
            EXIT WHEN CUR%NOTFOUND;
            STR:=STR||' OR UPPER(MANV)='''||USR||'''';
        END LOOP;
        Dbms_ouTput.Put_line(STR);
    END IF;
END;

/
EXEC P_TEST;
EXEC P_TRUONGPHONG_TEST;
SELECT * FROM NHANVIEN;
*/