CREATE OR REPLACE PROCEDURE PROC_INSERT_NHANSU(p_MANV     IN VARCHAR2,
    p_TENNV    IN VARCHAR2,
    p_PHAI     IN VARCHAR2,
    p_NGAYSINH IN VARCHAR2,
    p_DIACHI   IN VARCHAR2,
    p_SODT     IN VARCHAR2,
    p_VAITRO   IN VARCHAR2,
    p_MANQL    IN VARCHAR2,
    p_PHG      IN VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    INSERT INTO OLS_TEST1.V_NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG)
    VALUES (p_MANV, p_TENNV, p_PHAI, TO_DATE(p_NGAYSINH,'MM/DD/YYYY'), p_DIACHI, p_SODT, p_VAITRO, p_MANQL, p_PHG); 
    COMMIT;
END;
/
/
CREATE OR REPLACE PROCEDURE PROC_INSERT_PHANCONG(p_MANV VARCHAR2, p_MADA VARCHAR2,p_THOIGIAN VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    INSERT INTO PHANCONG(MANV,MADA,THOIGIAN)
    VALUES(p_MANV,p_MADA,TO_DATE(p_THOIGIAN,'MM/DD/YYYY'));
END;
/
CREATE OR REPLACE PROCEDURE PROC_INSERT_PHONGBAN(p_MAPB VARCHAR2, p_TENPB VARCHAR2,p_TRPHG VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    INSERT INTO PHONGBAN(MAPB,TENPB,TRPHG)
    VALUES(p_MAPB,p_TENPB,p_TRPHG);
END;
/
CREATE OR REPLACE PROCEDURE PROC_INSERT_DEAN(p_MADA VARCHAR2, p_TENDA VARCHAR2,p_NGAYBD VARCHAR2,p_PHONG VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    INSERT INTO DEAN(MADA,TENDA,NGAYBD,PHONG)
    VALUES(p_MADA,p_TENDA,TO_DATE(p_NGAYBD,'MM/DD/YYYY'),p_PHONG);
END;
/
CREATE OR REPLACE PROCEDURE PROC_UPDATE (COL VARCHAR2,VAL VARCHAR2, MA VARCHAR2,CONCOL VARCHAR2, TAB VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN 
    IF COL='NGAYSINH' OR COL='THOIGIAN' OR COL='NGAYBD' THEN
        STR:='UPDATE '||TAB||' SET '||COL||' = TO_DATE('''||VAL||''',''MM/DD/YYYY'') WHERE '||CONCOL||'= '''||MA||'''';
    ELSE
        STR:='UPDATE '||TAB||' SET '||COL||' = '''||VAL||''' WHERE '||CONCOL||'= '''||MA||'''';
    --Dbms_ouTput.Put_line(STR);
    END IF;
    EXECUTE IMMEDIATE(STR);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE PROC_UPDATE_PHANCONG (COL VARCHAR2,VAL VARCHAR2, MA VARCHAR2,MDA VARCHAR2, TAB VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN 
    IF COL='NGAYSINH' OR COL='THOIGIAN' OR COL='NGAYBD' THEN
        STR:='UPDATE '||TAB||' SET '||COL||' = TO_DATE('''||VAL||''',''MM/DD/YYYY'') WHERE MANV= '''||MA||''' AND MADA='''||MDA||'''';
    ELSE
        STR:='UPDATE '||TAB||' SET '||COL||' = '''||VAL||''' WHERE MANV= '''||MA||''' AND MADA='''||MDA||'''';
    --Dbms_ouTput.Put_line(STR);
    END IF;
    EXECUTE IMMEDIATE(STR);
    COMMIT;
END;

/

CREATE OR REPLACE PROCEDURE PROC_DELETE(COL VARCHAR2, VAL VARCHAR2, TAB VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    STR:='DELETE FROM '||TAB||' WHERE '||COL||' = '''||VAL||'''';
    EXECUTE IMMEDIATE(STR);
END;

/
CREATE OR REPLACE PROCEDURE PROC_DELETE_PHANCONG(VAL1 VARCHAR2, VAL2 VARCHAR2)
AS
    STR VARCHAR2(10000);
BEGIN
    STR:='DELETE FROM OLS_TEST1.PHANCONG WHERE MANV = '''||VAL1||'''AND MADA='''||VAL2||'''';
    EXECUTE IMMEDIATE(STR);
END;
/
--CAP QUYEN USER 

GRANT EXECUTE ON OLS_TEST1.PROC_INSERT_NHANSU TO NHANSU;
GRANT EXECUTE ON OLS_TEST1.PROC_UPDATE TO NHANVIEN,NHANSU,TRUONGPHONG,QUANLYTRUCTIEP,TAICHINH,TRUONGDEAN,BANGIAMDOC;
GRANT EXECUTE ON OLS_TEST1.PROC_INSERT_DEAN TO TRUONGDEAN;
GRANT EXECUTE ON OLS_TEST1.PROC_INSERT_PHANCONG TO TRUONGPHONG;
GRANT EXECUTE ON OLS_TEST1.PROC_DELETE TO NHANVIEN,NHANSU,TRUONGPHONG,QUANLYTRUCTIEP,TAICHINH,TRUONGDEAN,BANGIAMDOC;
GRANT EXECUTE ON OLS_TEST1.PROC_DELETE_PHANCONG TO TRUONGPHONG;
GRANT EXECUTE ON OLS_TEST1.PROC_INSERT_PHONGBAN TO TRUONGPHONG;
GRANT EXECUTE ON OLS_TEST1.PROC_UPDATE_PHANCONG TO TRUONGPHONG;
-- THE ANH CODE
GRANT SELECT ON OLS_TEST1.THONGBAO TO BANGIAMDOC;

